// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacestation.proto

package org.kimfri.protobuff;

public interface SpaceShipOrBuilder extends
        // @@protoc_insertion_point(interface_extends:doesthismatter.SpaceShip)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     *
     * @return Whether the name field is set.
     */
    boolean hasName();

    /**
     * <code>required string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>required string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>optional string cargo = 2;</code>
     *
     * @return Whether the cargo field is set.
     */
    boolean hasCargo();

    /**
     * <code>optional string cargo = 2;</code>
     *
     * @return The cargo.
     */
    java.lang.String getCargo();

    /**
     * <code>optional string cargo = 2;</code>
     *
     * @return The bytes for cargo.
     */
    com.google.protobuf.ByteString
    getCargoBytes();
}
