// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacestation.proto

package org.kimfri.protobuff;

public final class SpaceStationOuterClass {
  private SpaceStationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doesthismatter_Captain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doesthismatter_Captain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doesthismatter_SpaceShip_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doesthismatter_SpaceShip_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doesthismatter_SpaceStation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doesthismatter_SpaceStation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022spacestation.proto\022\016doesthismatter\"\027\n\007" +
      "Captain\022\014\n\004name\030\001 \002(\t\"(\n\tSpaceShip\022\014\n\004na" +
      "me\030\001 \002(\t\022\r\n\005cargo\030\002 \001(\t\"t\n\014SpaceStation\022" +
      "\014\n\004name\030\001 \002(\t\022(\n\007captain\030\002 \002(\0132\027.doesthi" +
      "smatter.Captain\022,\n\tspaceShip\030\003 \002(\0132\031.doe" +
      "sthismatter.SpaceShipB0\n\024org.kimfri.prot" +
      "obuffB\026SpaceStationOuterClassP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_doesthismatter_Captain_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_doesthismatter_Captain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doesthismatter_Captain_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_doesthismatter_SpaceShip_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_doesthismatter_SpaceShip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doesthismatter_SpaceShip_descriptor,
        new java.lang.String[] { "Name", "Cargo", });
    internal_static_doesthismatter_SpaceStation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_doesthismatter_SpaceStation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doesthismatter_SpaceStation_descriptor,
        new java.lang.String[] { "Name", "Captain", "SpaceShip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
