// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacestation.proto

package org.kimfri.protobuff;

/**
 * Protobuf type {@code doesthismatter.SpaceStation}
 */
public final class SpaceStation extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:doesthismatter.SpaceStation)
        SpaceStationOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use SpaceStation.newBuilder() to construct.
    private SpaceStation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private SpaceStation() {
        name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new SpaceStation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private SpaceStation(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000001;
                        name_ = bs;
                        break;
                    }
                    case 18: {
                        org.kimfri.protobuff.Captain.Builder subBuilder = null;
                        if (((bitField0_ & 0x00000002) != 0)) {
                            subBuilder = captain_.toBuilder();
                        }
                        captain_ = input.readMessage(org.kimfri.protobuff.Captain.PARSER, extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(captain_);
                            captain_ = subBuilder.buildPartial();
                        }
                        bitField0_ |= 0x00000002;
                        break;
                    }
                    case 26: {
                        org.kimfri.protobuff.SpaceShip.Builder subBuilder = null;
                        if (((bitField0_ & 0x00000004) != 0)) {
                            subBuilder = spaceShip_.toBuilder();
                        }
                        spaceShip_ = input.readMessage(org.kimfri.protobuff.SpaceShip.PARSER, extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(spaceShip_);
                            spaceShip_ = subBuilder.buildPartial();
                        }
                        bitField0_ |= 0x00000004;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.kimfri.protobuff.SpaceStationOuterClass.internal_static_doesthismatter_SpaceStation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.kimfri.protobuff.SpaceStationOuterClass.internal_static_doesthismatter_SpaceStation_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.kimfri.protobuff.SpaceStation.class, org.kimfri.protobuff.SpaceStation.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;

    /**
     * <code>required string name = 1;</code>
     *
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>required string name = 1;</code>
     *
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                name_ = s;
            }
            return s;
        }
    }

    /**
     * <code>required string name = 1;</code>
     *
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CAPTAIN_FIELD_NUMBER = 2;
    private org.kimfri.protobuff.Captain captain_;

    /**
     * <code>required .doesthismatter.Captain captain = 2;</code>
     *
     * @return Whether the captain field is set.
     */
    @java.lang.Override
    public boolean hasCaptain() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>required .doesthismatter.Captain captain = 2;</code>
     *
     * @return The captain.
     */
    @java.lang.Override
    public org.kimfri.protobuff.Captain getCaptain() {
        return captain_ == null ? org.kimfri.protobuff.Captain.getDefaultInstance() : captain_;
    }

    /**
     * <code>required .doesthismatter.Captain captain = 2;</code>
     */
    @java.lang.Override
    public org.kimfri.protobuff.CaptainOrBuilder getCaptainOrBuilder() {
        return captain_ == null ? org.kimfri.protobuff.Captain.getDefaultInstance() : captain_;
    }

    public static final int SPACESHIP_FIELD_NUMBER = 3;
    private org.kimfri.protobuff.SpaceShip spaceShip_;

    /**
     * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
     *
     * @return Whether the spaceShip field is set.
     */
    @java.lang.Override
    public boolean hasSpaceShip() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
     *
     * @return The spaceShip.
     */
    @java.lang.Override
    public org.kimfri.protobuff.SpaceShip getSpaceShip() {
        return spaceShip_ == null ? org.kimfri.protobuff.SpaceShip.getDefaultInstance() : spaceShip_;
    }

    /**
     * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
     */
    @java.lang.Override
    public org.kimfri.protobuff.SpaceShipOrBuilder getSpaceShipOrBuilder() {
        return spaceShip_ == null ? org.kimfri.protobuff.SpaceShip.getDefaultInstance() : spaceShip_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasName()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasCaptain()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasSpaceShip()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!getCaptain().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!getSpaceShip().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            output.writeMessage(2, getCaptain());
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            output.writeMessage(3, getSpaceShip());
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, getCaptain());
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, getSpaceShip());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.kimfri.protobuff.SpaceStation)) {
            return super.equals(obj);
        }
        org.kimfri.protobuff.SpaceStation other = (org.kimfri.protobuff.SpaceStation) obj;

        if (hasName() != other.hasName()) return false;
        if (hasName()) {
            if (!getName()
                    .equals(other.getName())) return false;
        }
        if (hasCaptain() != other.hasCaptain()) return false;
        if (hasCaptain()) {
            if (!getCaptain()
                    .equals(other.getCaptain())) return false;
        }
        if (hasSpaceShip() != other.hasSpaceShip()) return false;
        if (hasSpaceShip()) {
            if (!getSpaceShip()
                    .equals(other.getSpaceShip())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasName()) {
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
        }
        if (hasCaptain()) {
            hash = (37 * hash) + CAPTAIN_FIELD_NUMBER;
            hash = (53 * hash) + getCaptain().hashCode();
        }
        if (hasSpaceShip()) {
            hash = (37 * hash) + SPACESHIP_FIELD_NUMBER;
            hash = (53 * hash) + getSpaceShip().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.kimfri.protobuff.SpaceStation parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.kimfri.protobuff.SpaceStation parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.kimfri.protobuff.SpaceStation parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.kimfri.protobuff.SpaceStation prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code doesthismatter.SpaceStation}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:doesthismatter.SpaceStation)
            org.kimfri.protobuff.SpaceStationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.kimfri.protobuff.SpaceStationOuterClass.internal_static_doesthismatter_SpaceStation_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.kimfri.protobuff.SpaceStationOuterClass.internal_static_doesthismatter_SpaceStation_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.kimfri.protobuff.SpaceStation.class, org.kimfri.protobuff.SpaceStation.Builder.class);
        }

        // Construct using org.kimfri.protobuff.SpaceStation.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getCaptainFieldBuilder();
                getSpaceShipFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            name_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            if (captainBuilder_ == null) {
                captain_ = null;
            } else {
                captainBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            if (spaceShipBuilder_ == null) {
                spaceShip_ = null;
            } else {
                spaceShipBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000004);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return org.kimfri.protobuff.SpaceStationOuterClass.internal_static_doesthismatter_SpaceStation_descriptor;
        }

        @java.lang.Override
        public org.kimfri.protobuff.SpaceStation getDefaultInstanceForType() {
            return org.kimfri.protobuff.SpaceStation.getDefaultInstance();
        }

        @java.lang.Override
        public org.kimfri.protobuff.SpaceStation build() {
            org.kimfri.protobuff.SpaceStation result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.kimfri.protobuff.SpaceStation buildPartial() {
            org.kimfri.protobuff.SpaceStation result = new org.kimfri.protobuff.SpaceStation(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                to_bitField0_ |= 0x00000001;
            }
            result.name_ = name_;
            if (((from_bitField0_ & 0x00000002) != 0)) {
                if (captainBuilder_ == null) {
                    result.captain_ = captain_;
                } else {
                    result.captain_ = captainBuilder_.build();
                }
                to_bitField0_ |= 0x00000002;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                if (spaceShipBuilder_ == null) {
                    result.spaceShip_ = spaceShip_;
                } else {
                    result.spaceShip_ = spaceShipBuilder_.build();
                }
                to_bitField0_ |= 0x00000004;
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.kimfri.protobuff.SpaceStation) {
                return mergeFrom((org.kimfri.protobuff.SpaceStation) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.kimfri.protobuff.SpaceStation other) {
            if (other == org.kimfri.protobuff.SpaceStation.getDefaultInstance()) return this;
            if (other.hasName()) {
                bitField0_ |= 0x00000001;
                name_ = other.name_;
                onChanged();
            }
            if (other.hasCaptain()) {
                mergeCaptain(other.getCaptain());
            }
            if (other.hasSpaceShip()) {
                mergeSpaceShip(other.getSpaceShip());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            if (!hasName()) {
                return false;
            }
            if (!hasCaptain()) {
                return false;
            }
            if (!hasSpaceShip()) {
                return false;
            }
            if (!getCaptain().isInitialized()) {
                return false;
            }
            if (!getSpaceShip().isInitialized()) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            org.kimfri.protobuff.SpaceStation parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (org.kimfri.protobuff.SpaceStation) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.lang.Object name_ = "";

        /**
         * <code>required string name = 1;</code>
         *
         * @return Whether the name field is set.
         */
        public boolean hasName() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required string name = 1;</code>
         *
         * @return The name.
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    name_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>required string name = 1;</code>
         *
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>required string name = 1;</code>
         *
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>required string name = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearName() {
            bitField0_ = (bitField0_ & ~0x00000001);
            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
        }

        /**
         * <code>required string name = 1;</code>
         *
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            name_ = value;
            onChanged();
            return this;
        }

        private org.kimfri.protobuff.Captain captain_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.kimfri.protobuff.Captain, org.kimfri.protobuff.Captain.Builder, org.kimfri.protobuff.CaptainOrBuilder> captainBuilder_;

        /**
         * <code>required .doesthismatter.Captain captain = 2;</code>
         *
         * @return Whether the captain field is set.
         */
        public boolean hasCaptain() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required .doesthismatter.Captain captain = 2;</code>
         *
         * @return The captain.
         */
        public org.kimfri.protobuff.Captain getCaptain() {
            if (captainBuilder_ == null) {
                return captain_ == null ? org.kimfri.protobuff.Captain.getDefaultInstance() : captain_;
            } else {
                return captainBuilder_.getMessage();
            }
        }

        /**
         * <code>required .doesthismatter.Captain captain = 2;</code>
         */
        public Builder setCaptain(org.kimfri.protobuff.Captain value) {
            if (captainBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                captain_ = value;
                onChanged();
            } else {
                captainBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000002;
            return this;
        }

        /**
         * <code>required .doesthismatter.Captain captain = 2;</code>
         */
        public Builder setCaptain(
                org.kimfri.protobuff.Captain.Builder builderForValue) {
            if (captainBuilder_ == null) {
                captain_ = builderForValue.build();
                onChanged();
            } else {
                captainBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000002;
            return this;
        }

        /**
         * <code>required .doesthismatter.Captain captain = 2;</code>
         */
        public Builder mergeCaptain(org.kimfri.protobuff.Captain value) {
            if (captainBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0) &&
                        captain_ != null &&
                        captain_ != org.kimfri.protobuff.Captain.getDefaultInstance()) {
                    captain_ =
                            org.kimfri.protobuff.Captain.newBuilder(captain_).mergeFrom(value).buildPartial();
                } else {
                    captain_ = value;
                }
                onChanged();
            } else {
                captainBuilder_.mergeFrom(value);
            }
            bitField0_ |= 0x00000002;
            return this;
        }

        /**
         * <code>required .doesthismatter.Captain captain = 2;</code>
         */
        public Builder clearCaptain() {
            if (captainBuilder_ == null) {
                captain_ = null;
                onChanged();
            } else {
                captainBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
        }

        /**
         * <code>required .doesthismatter.Captain captain = 2;</code>
         */
        public org.kimfri.protobuff.Captain.Builder getCaptainBuilder() {
            bitField0_ |= 0x00000002;
            onChanged();
            return getCaptainFieldBuilder().getBuilder();
        }

        /**
         * <code>required .doesthismatter.Captain captain = 2;</code>
         */
        public org.kimfri.protobuff.CaptainOrBuilder getCaptainOrBuilder() {
            if (captainBuilder_ != null) {
                return captainBuilder_.getMessageOrBuilder();
            } else {
                return captain_ == null ?
                        org.kimfri.protobuff.Captain.getDefaultInstance() : captain_;
            }
        }

        /**
         * <code>required .doesthismatter.Captain captain = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.kimfri.protobuff.Captain, org.kimfri.protobuff.Captain.Builder, org.kimfri.protobuff.CaptainOrBuilder>
        getCaptainFieldBuilder() {
            if (captainBuilder_ == null) {
                captainBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.kimfri.protobuff.Captain, org.kimfri.protobuff.Captain.Builder, org.kimfri.protobuff.CaptainOrBuilder>(
                        getCaptain(),
                        getParentForChildren(),
                        isClean());
                captain_ = null;
            }
            return captainBuilder_;
        }

        private org.kimfri.protobuff.SpaceShip spaceShip_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.kimfri.protobuff.SpaceShip, org.kimfri.protobuff.SpaceShip.Builder, org.kimfri.protobuff.SpaceShipOrBuilder> spaceShipBuilder_;

        /**
         * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
         *
         * @return Whether the spaceShip field is set.
         */
        public boolean hasSpaceShip() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
         *
         * @return The spaceShip.
         */
        public org.kimfri.protobuff.SpaceShip getSpaceShip() {
            if (spaceShipBuilder_ == null) {
                return spaceShip_ == null ? org.kimfri.protobuff.SpaceShip.getDefaultInstance() : spaceShip_;
            } else {
                return spaceShipBuilder_.getMessage();
            }
        }

        /**
         * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
         */
        public Builder setSpaceShip(org.kimfri.protobuff.SpaceShip value) {
            if (spaceShipBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                spaceShip_ = value;
                onChanged();
            } else {
                spaceShipBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000004;
            return this;
        }

        /**
         * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
         */
        public Builder setSpaceShip(
                org.kimfri.protobuff.SpaceShip.Builder builderForValue) {
            if (spaceShipBuilder_ == null) {
                spaceShip_ = builderForValue.build();
                onChanged();
            } else {
                spaceShipBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000004;
            return this;
        }

        /**
         * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
         */
        public Builder mergeSpaceShip(org.kimfri.protobuff.SpaceShip value) {
            if (spaceShipBuilder_ == null) {
                if (((bitField0_ & 0x00000004) != 0) &&
                        spaceShip_ != null &&
                        spaceShip_ != org.kimfri.protobuff.SpaceShip.getDefaultInstance()) {
                    spaceShip_ =
                            org.kimfri.protobuff.SpaceShip.newBuilder(spaceShip_).mergeFrom(value).buildPartial();
                } else {
                    spaceShip_ = value;
                }
                onChanged();
            } else {
                spaceShipBuilder_.mergeFrom(value);
            }
            bitField0_ |= 0x00000004;
            return this;
        }

        /**
         * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
         */
        public Builder clearSpaceShip() {
            if (spaceShipBuilder_ == null) {
                spaceShip_ = null;
                onChanged();
            } else {
                spaceShipBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000004);
            return this;
        }

        /**
         * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
         */
        public org.kimfri.protobuff.SpaceShip.Builder getSpaceShipBuilder() {
            bitField0_ |= 0x00000004;
            onChanged();
            return getSpaceShipFieldBuilder().getBuilder();
        }

        /**
         * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
         */
        public org.kimfri.protobuff.SpaceShipOrBuilder getSpaceShipOrBuilder() {
            if (spaceShipBuilder_ != null) {
                return spaceShipBuilder_.getMessageOrBuilder();
            } else {
                return spaceShip_ == null ?
                        org.kimfri.protobuff.SpaceShip.getDefaultInstance() : spaceShip_;
            }
        }

        /**
         * <code>required .doesthismatter.SpaceShip spaceShip = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.kimfri.protobuff.SpaceShip, org.kimfri.protobuff.SpaceShip.Builder, org.kimfri.protobuff.SpaceShipOrBuilder>
        getSpaceShipFieldBuilder() {
            if (spaceShipBuilder_ == null) {
                spaceShipBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.kimfri.protobuff.SpaceShip, org.kimfri.protobuff.SpaceShip.Builder, org.kimfri.protobuff.SpaceShipOrBuilder>(
                        getSpaceShip(),
                        getParentForChildren(),
                        isClean());
                spaceShip_ = null;
            }
            return spaceShipBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:doesthismatter.SpaceStation)
    }

    // @@protoc_insertion_point(class_scope:doesthismatter.SpaceStation)
    private static final org.kimfri.protobuff.SpaceStation DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new org.kimfri.protobuff.SpaceStation();
    }

    public static org.kimfri.protobuff.SpaceStation getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<SpaceStation>
            PARSER = new com.google.protobuf.AbstractParser<SpaceStation>() {
        @java.lang.Override
        public SpaceStation parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new SpaceStation(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<SpaceStation> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpaceStation> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public org.kimfri.protobuff.SpaceStation getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

